name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instructlab gitpython
        echo "Dependencies installed successfully"

    - name: Clone custom taxonomy repository
      run: |
        git clone https://github.com/nicklamb97/taxonomy.git taxonomy
        echo "Custom taxonomy repository cloned successfully"

    - name: Initialise ilab
      run: |
        echo -e "taxonomy\nn" | ilab config init
        echo "ilab initialised successfully"

    - name: Get diff and generate data
      run: |
        cd taxonomy
        git fetch origin
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        echo "Previous commit: $PREVIOUS_COMMIT"
        echo "Current commit: $CURRENT_COMMIT"
        
        # Get list of added or modified files
        CHANGED_FILES=$(git diff --name-only --diff-filter=AM $PREVIOUS_COMMIT $CURRENT_COMMIT)
        echo "Changed files:"
        echo "$CHANGED_FILES"
        
        # Check if any qna.yaml files were changed
        if echo "$CHANGED_FILES" | grep -q "qna.yaml"; then
          echo "Changes detected in qna.yaml files. Generating data..."
          cd ..
          echo "Current directory: $(pwd)"
          echo "Running: ilab taxonomy diff"
          ilab taxonomy diff
          echo "Running: ilab data generate"
          ilab data generate
          echo "Data generation complete"
          
          # Set a flag to indicate that data was generated
          echo "DATA_GENERATED=true" >> $GITHUB_ENV
        else
          echo "No changes detected in qna.yaml files. Skipping data generation."
          echo "DATA_GENERATED=false" >> $GITHUB_ENV
        fi

    - name: Download model
      if: env.DATA_GENERATED == 'true'
      run: |
        echo "Data was generated, downloading model..."
        ilab model download
        echo "Model downloaded successfully"

    - name: Commit and push generated data
      if: env.DATA_GENERATED == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "Git user configured"
        if [ -d "generated" ]; then
          echo "Generated directory found"
          git add generated/
          git commit -m "Auto-generate data" || echo "No changes to commit"
          git push
          echo "Changes pushed to repository"
        else
          echo "No generated directory found. Nothing to commit."
        fi