name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instructlab

    - name: Clone custom taxonomy repository
      run: |
        git clone https://github.com/YOUR_USERNAME/taxonomy.git taxonomy

    - name: Initialize ilab
      run: |
        echo -e "taxonomy\nn" | ilab config init

    - name: Create newly added files
      run: |
        cd taxonomy
        git fetch origin
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        git diff --name-status $PREVIOUS_COMMIT $CURRENT_COMMIT | while read status file; do
          if [ "$status" == "A" ]; then
            echo "Creating new file: $file"
            mkdir -p $(dirname "$file")
            git show $CURRENT_COMMIT:"$file" > "$file"
          fi
        done
        cd ..

    - name: Run ilab diff
      run: |
        ilab taxonomy diff

    - name: Generate data
      run: |
        ilab data generate

    - name: Download model
      run: ilab model download

    - name: Commit and push generated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated/
        git commit -m "Auto-generate data" || echo "No changes to commit"
        git push
