name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instructlab gitpython

    - name: Clone custom taxonomy repository
      run: |
        git clone https://github.com/nicklamb97/taxonomy.git taxonomy

    - name: Initialize ilab
      run: |
        echo -e "taxonomy\nn" | ilab config init

    - name: Get diff and generate data
      run: |
        cd taxonomy
        git fetch origin
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        
        # Get list of added or modified files
        CHANGED_FILES=$(git diff --name-only --diff-filter=AM $PREVIOUS_COMMIT $CURRENT_COMMIT)
        
        # Check if any qna.yaml files were changed
        if echo "$CHANGED_FILES" | grep -q "qna.yaml"; then
          echo "Changes detected in qna.yaml files. Generating data..."
          cd ..
          ilab taxonomy diff
          ilab data generate
        else
          echo "No changes detected in qna.yaml files. Skipping data generation."
        fi

    - name: Download model
      run: ilab model download

    - name: Commit and push generated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -d "generated" ]; then
          git add generated/
          git commit -m "Auto-generate data" || echo "No changes to commit"
          git push
        else
          echo "No generated data to commit"
        fi