name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython
        echo "Dependencies installed successfully"

    - name: Clone custom taxonomy repository
      run: |
        git clone https://github.com/nicklamb97/taxonomy.git $GITHUB_WORKSPACE/taxonomy
        echo "Custom taxonomy repository cloned successfully"

    - name: Create basic YAML file
      run: |
        mkdir -p $GITHUB_WORKSPACE/generated
        echo "version: 1.0" > $GITHUB_WORKSPACE/generated/test_config.yaml
        echo "name: Test Configuration File" >> $GITHUB_WORKSPACE/generated/test_config_copy.yaml
        echo "description: This is a basic YAML file for testing purposes" >> $GITHUB_WORKSPACE/generated/test_config.yaml
        echo "Basic YAML file created successfully"

    - name: Commit and push to separate repository
      env:
        GITHUB_TOKEN: ${{ secrets.GENERATED_REPO_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE
        if [ -d "generated" ]; then
          echo "Generated files directory found"
          git clone https://github.com/nicklamb97/generated.git temp_generated
          cd temp_generated
          git config user.name "Nick Lamb"
          git config user.email "nick.lamb@diegesis.co.uk"
          cp -r ../generated/* .
          git add .
          git commit -m "Add test configuration file" || echo "No changes to commit"
          git push https://$GITHUB_TOKEN@github.com/nicklamb97/generated.git main
          echo "Changes pushed to generated repository"
          cd ..
          rm -rf temp_generated
        else
          echo "No generated files directory found. Nothing to commit."
        fi