name: Generate Synthetic Data for InstructLab

on:
  push:
    branches:
      - main

jobs:
  Generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instructlab gitpython
        echo "Dependencies installed successfully"

    - name: Clone custom taxonomy repository
      run: |
        git clone "https://github.com/nicklamb97/taxonomy.git" "$GITHUB_WORKSPACE/taxonomy"
        echo "Custom taxonomy repository cloned successfully"

    - name: Clone and copy config.yaml
      run: |
        git clone "https://github.com/nicklamb97/instructlab-config.git" temp_config
        cp temp_config/config.yaml "$GITHUB_WORKSPACE/config.yaml"
        rm -rf temp_config
        echo "config.yaml copied to root directory"

    - name: Download model
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Downloading Meta-Llama-3-8B-Instruct model..."
        HF_TOKEN=$HF_TOKEN ilab model download --repository=QuantFactory/Meta-Llama-3-8B-Instruct-GGUF --filename=Meta-Llama-3-8B-Instruct.Q4_K_M.gguf
        echo "Model downloaded successfully"
        echo "MODEL_DOWNLOADED=true" >> "$GITHUB_ENV"

    - name: Get diff and prepare for data generation
      run: |
        cd "$GITHUB_WORKSPACE/taxonomy"
        git config --local user.name "Nick Lamb"
        git config --local user.email "nick.lamb@diegesis.co.uk"
        git fetch origin
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        echo "Previous commit: $PREVIOUS_COMMIT"
        echo "Current commit: $CURRENT_COMMIT"
        
        CHANGED_FILES=$(git diff --name-only --diff-filter=AM "$PREVIOUS_COMMIT" "$CURRENT_COMMIT")
        echo "Changed files:"
        echo "$CHANGED_FILES"
        
        if echo "$CHANGED_FILES" | grep -q "qna.yaml"; then
          echo "Changes detected in qna.yaml files. Preparing for data generation..."
          git checkout -b temp_branch
          git reset --hard "$PREVIOUS_COMMIT"
          git cherry-pick "$CURRENT_COMMIT"
          echo "Changes applied to temporary branch. Ready for ilab taxonomy diff."
          echo "QNA_YAML_CHANGED=true" >> "$GITHUB_ENV"
        else
          echo "No changes detected in qna.yaml files. Skipping data generation."
          echo "QNA_YAML_CHANGED=false" >> "$GITHUB_ENV"
        fi

    - name: Run ilab taxonomy diff and generate data
      if: env.QNA_YAML_CHANGED == 'true' && env.MODEL_DOWNLOADED == 'true'
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "Current directory: $(pwd)"
        echo "Running: ilab taxonomy diff"
        ilab taxonomy diff || { echo "ilab taxonomy diff failed. Exiting gracefully."; exit 0; }
        echo "Running: ilab data generate"
        ilab data generate --output-dir ./generated || { echo "ilab data generate failed. Exiting gracefully."; exit 0; }

    - name: No qna.yaml changes or model not downloaded
      if: env.QNA_YAML_CHANGED == 'false' || env.MODEL_DOWNLOADED != 'true'
      run: |
        if [ "$QNA_YAML_CHANGED" = "false" ]; then
          echo "No qna.yaml files were changed. Skipping ilab taxonomy diff and data generation."
        fi
        if [ "$MODEL_DOWNLOADED" != "true" ]; then
          echo "Model was not downloaded successfully. Skipping data generation."
        fi

    - name: Commit and push generated data to separate repository
      if: env.QNA_YAML_CHANGED == 'true' && env.MODEL_DOWNLOADED == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GENERATED_REPO_TOKEN }}
      run: |
        cd "$GITHUB_WORKSPACE"
        if [ -d "generated" ]; then
          echo "Generated files directory found"
          git clone "https://github.com/nicklamb97/generated.git" temp_generated
          cd temp_generated
          git config user.name "Nick Lamb"
          git config user.email "nick.lamb@diegesis.co.uk"
          cp -r ../generated/* .
          git add .
          git commit -m "Auto-generated synthetic data" || echo "No changes to commit"
          git push "https://$GITHUB_TOKEN@github.com/nicklamb97/generated.git" main
          echo "Changes pushed to generated repository"
          cd ..
          rm -rf temp_generated
        else
          echo "No generated directory found. Nothing to commit."
        fi
