name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instructlab gitpython
        echo "Dependencies installed successfully"

    - name: Clone custom taxonomy repository
      run: |
        git clone https://github.com/nicklamb97/taxonomy.git taxonomy
        echo "Custom taxonomy repository cloned successfully"

    - name: Initialise ilab
      run: |
        echo -e "taxonomy\nn" | ilab config init
        echo "ilab initialised successfully"

    - name: Download model
      run: |
        echo "Downloading model..."
        ilab model download
        echo "Model downloaded successfully"
        echo "MODEL_DOWNLOADED=true" >> $GITHUB_ENV

    - name: Get diff and prepare for data generation
      run: |
        cd taxonomy
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git fetch origin
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        echo "Previous commit: $PREVIOUS_COMMIT"
        echo "Current commit: $CURRENT_COMMIT"
        
        # Get list of added or modified files
        CHANGED_FILES=$(git diff --name-only --diff-filter=AM $PREVIOUS_COMMIT $CURRENT_COMMIT)
        echo "Changed files:"
        echo "$CHANGED_FILES"
        
        # Check if any qna.yaml files were changed
        if echo "$CHANGED_FILES" | grep -q "qna.yaml"; then
          echo "Changes detected in qna.yaml files. Preparing for data generation..."
          
          # Create a temporary branch
          git checkout -b temp_branch
          
          # Reset to the previous commit
          git reset --hard $PREVIOUS_COMMIT
          
          # Apply the changes from the current commit
          git cherry-pick $CURRENT_COMMIT
          
          echo "Changes applied to temporary branch. Ready for ilab taxonomy diff."
          echo "QNA_YAML_CHANGED=true" >> $GITHUB_ENV
        else
          echo "No changes detected in qna.yaml files. Skipping data generation."
          echo "QNA_YAML_CHANGED=false" >> $GITHUB_ENV

    - name: Run ilab taxonomy diff and generate data
      if: env.QNA_YAML_CHANGED == 'true' && env.MODEL_DOWNLOADED == 'true'
      run: |
        cd ..
        echo "Current directory: $(pwd)"
        echo "Running: ilab taxonomy diff"
        ilab taxonomy diff || { echo "ilab taxonomy diff failed. Exiting gracefully."; exit 0; }
        echo "Running: ilab data generate"
        ilab data generate --output-dir ./taxonomy/generated || { echo "ilab data generate failed. Exiting gracefully."; exit 0; }

    - name: No qna.yaml changes or model not downloaded
      if: env.QNA_YAML_CHANGED == 'false' || env.MODEL_DOWNLOADED != 'true'
      run: |
        if [ "$QNA_YAML_CHANGED" = "false" ]; then
          echo "No qna.yaml files were changed. Skipping ilab taxonomy diff and data generation."
        fi
        if [ "$MODEL_DOWNLOADED" != "true" ]; then
          echo "Model was not downloaded successfully. Skipping data generation."
        fi

    - name: Commit and push generated data
      if: env.QNA_YAML_CHANGED == 'true' && env.MODEL_DOWNLOADED == 'true'
      run: |
        cd taxonomy
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "Git user configured"
        if [ -d "generated" ]; then
          echo "Generated directory found"
          git add generated/
          git commit -m "Auto-generate data" || echo "No changes to commit"
          git push origin main
          echo "Changes pushed to repository"
        else
          echo "No generated directory found. Nothing to commit."
        fi