name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instructlab

    - name: Clone custom taxonomy repository
      run: |
        git clone https://github.com/nicklamb97/taxonomy.git taxonomy

    - name: Initialize ilab
      run: |
        echo -e "taxonomy\nn" | ilab config init

    - name: Update custom taxonomy
      run: |
        cd taxonomy
        git pull
        cd ..

    - name: Run ilab diff
      run: |
        ilab taxonomy diff

    - name: Download model
      run: ilab model download

    - name: Generate data
      run: ilab data generate

    - name: Commit and push generated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated/
        git commit -m "Auto-generate data" || echo "No changes to commit"
        git push